//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.ServiceCenter.Statistics {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Statistics.IServiceStatistics")]
    public interface IServiceStatistics {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStatistics/AgeCnts", ReplyAction="http://tempuri.org/IServiceStatistics/AgeCntsResponse")]
        System.Data.DataTable AgeCnts();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceStatistics/AgeCnts", ReplyAction="http://tempuri.org/IServiceStatistics/AgeCntsResponse")]
        System.IAsyncResult BeginAgeCnts(System.AsyncCallback callback, object asyncState);
        
        System.Data.DataTable EndAgeCnts(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStatistics/AddrCnts", ReplyAction="http://tempuri.org/IServiceStatistics/AddrCntsResponse")]
        System.Data.DataTable AddrCnts();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceStatistics/AddrCnts", ReplyAction="http://tempuri.org/IServiceStatistics/AddrCntsResponse")]
        System.IAsyncResult BeginAddrCnts(System.AsyncCallback callback, object asyncState);
        
        System.Data.DataTable EndAddrCnts(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStatistics/DateCnts", ReplyAction="http://tempuri.org/IServiceStatistics/DateCntsResponse")]
        System.Data.DataTable DateCnts();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceStatistics/DateCnts", ReplyAction="http://tempuri.org/IServiceStatistics/DateCntsResponse")]
        System.IAsyncResult BeginDateCnts(System.AsyncCallback callback, object asyncState);
        
        System.Data.DataTable EndDateCnts(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStatistics/NameTags", ReplyAction="http://tempuri.org/IServiceStatistics/NameTagsResponse")]
        System.Data.DataTable NameTags();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceStatistics/NameTags", ReplyAction="http://tempuri.org/IServiceStatistics/NameTagsResponse")]
        System.IAsyncResult BeginNameTags(System.AsyncCallback callback, object asyncState);
        
        System.Data.DataTable EndNameTags(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceStatisticsChannel : PW.ServiceCenter.Statistics.IServiceStatistics, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgeCntsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AgeCntsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Data.DataTable Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddrCntsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddrCntsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Data.DataTable Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DateCntsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DateCntsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Data.DataTable Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NameTagsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public NameTagsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Data.DataTable Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceStatisticsClient : System.ServiceModel.ClientBase<PW.ServiceCenter.Statistics.IServiceStatistics>, PW.ServiceCenter.Statistics.IServiceStatistics {
        
        private BeginOperationDelegate onBeginAgeCntsDelegate;
        
        private EndOperationDelegate onEndAgeCntsDelegate;
        
        private System.Threading.SendOrPostCallback onAgeCntsCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddrCntsDelegate;
        
        private EndOperationDelegate onEndAddrCntsDelegate;
        
        private System.Threading.SendOrPostCallback onAddrCntsCompletedDelegate;
        
        private BeginOperationDelegate onBeginDateCntsDelegate;
        
        private EndOperationDelegate onEndDateCntsDelegate;
        
        private System.Threading.SendOrPostCallback onDateCntsCompletedDelegate;
        
        private BeginOperationDelegate onBeginNameTagsDelegate;
        
        private EndOperationDelegate onEndNameTagsDelegate;
        
        private System.Threading.SendOrPostCallback onNameTagsCompletedDelegate;
        
        public ServiceStatisticsClient() {
        }
        
        public ServiceStatisticsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceStatisticsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceStatisticsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceStatisticsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<AgeCntsCompletedEventArgs> AgeCntsCompleted;
        
        public event System.EventHandler<AddrCntsCompletedEventArgs> AddrCntsCompleted;
        
        public event System.EventHandler<DateCntsCompletedEventArgs> DateCntsCompleted;
        
        public event System.EventHandler<NameTagsCompletedEventArgs> NameTagsCompleted;
        
        public System.Data.DataTable AgeCnts() {
            return base.Channel.AgeCnts();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAgeCnts(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAgeCnts(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Data.DataTable EndAgeCnts(System.IAsyncResult result) {
            return base.Channel.EndAgeCnts(result);
        }
        
        private System.IAsyncResult OnBeginAgeCnts(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginAgeCnts(callback, asyncState);
        }
        
        private object[] OnEndAgeCnts(System.IAsyncResult result) {
            System.Data.DataTable retVal = this.EndAgeCnts(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAgeCntsCompleted(object state) {
            if ((this.AgeCntsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AgeCntsCompleted(this, new AgeCntsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AgeCntsAsync() {
            this.AgeCntsAsync(null);
        }
        
        public void AgeCntsAsync(object userState) {
            if ((this.onBeginAgeCntsDelegate == null)) {
                this.onBeginAgeCntsDelegate = new BeginOperationDelegate(this.OnBeginAgeCnts);
            }
            if ((this.onEndAgeCntsDelegate == null)) {
                this.onEndAgeCntsDelegate = new EndOperationDelegate(this.OnEndAgeCnts);
            }
            if ((this.onAgeCntsCompletedDelegate == null)) {
                this.onAgeCntsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAgeCntsCompleted);
            }
            base.InvokeAsync(this.onBeginAgeCntsDelegate, null, this.onEndAgeCntsDelegate, this.onAgeCntsCompletedDelegate, userState);
        }
        
        public System.Data.DataTable AddrCnts() {
            return base.Channel.AddrCnts();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAddrCnts(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddrCnts(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Data.DataTable EndAddrCnts(System.IAsyncResult result) {
            return base.Channel.EndAddrCnts(result);
        }
        
        private System.IAsyncResult OnBeginAddrCnts(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginAddrCnts(callback, asyncState);
        }
        
        private object[] OnEndAddrCnts(System.IAsyncResult result) {
            System.Data.DataTable retVal = this.EndAddrCnts(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddrCntsCompleted(object state) {
            if ((this.AddrCntsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddrCntsCompleted(this, new AddrCntsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddrCntsAsync() {
            this.AddrCntsAsync(null);
        }
        
        public void AddrCntsAsync(object userState) {
            if ((this.onBeginAddrCntsDelegate == null)) {
                this.onBeginAddrCntsDelegate = new BeginOperationDelegate(this.OnBeginAddrCnts);
            }
            if ((this.onEndAddrCntsDelegate == null)) {
                this.onEndAddrCntsDelegate = new EndOperationDelegate(this.OnEndAddrCnts);
            }
            if ((this.onAddrCntsCompletedDelegate == null)) {
                this.onAddrCntsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddrCntsCompleted);
            }
            base.InvokeAsync(this.onBeginAddrCntsDelegate, null, this.onEndAddrCntsDelegate, this.onAddrCntsCompletedDelegate, userState);
        }
        
        public System.Data.DataTable DateCnts() {
            return base.Channel.DateCnts();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginDateCnts(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDateCnts(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Data.DataTable EndDateCnts(System.IAsyncResult result) {
            return base.Channel.EndDateCnts(result);
        }
        
        private System.IAsyncResult OnBeginDateCnts(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginDateCnts(callback, asyncState);
        }
        
        private object[] OnEndDateCnts(System.IAsyncResult result) {
            System.Data.DataTable retVal = this.EndDateCnts(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDateCntsCompleted(object state) {
            if ((this.DateCntsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DateCntsCompleted(this, new DateCntsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DateCntsAsync() {
            this.DateCntsAsync(null);
        }
        
        public void DateCntsAsync(object userState) {
            if ((this.onBeginDateCntsDelegate == null)) {
                this.onBeginDateCntsDelegate = new BeginOperationDelegate(this.OnBeginDateCnts);
            }
            if ((this.onEndDateCntsDelegate == null)) {
                this.onEndDateCntsDelegate = new EndOperationDelegate(this.OnEndDateCnts);
            }
            if ((this.onDateCntsCompletedDelegate == null)) {
                this.onDateCntsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDateCntsCompleted);
            }
            base.InvokeAsync(this.onBeginDateCntsDelegate, null, this.onEndDateCntsDelegate, this.onDateCntsCompletedDelegate, userState);
        }
        
        public System.Data.DataTable NameTags() {
            return base.Channel.NameTags();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginNameTags(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginNameTags(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Data.DataTable EndNameTags(System.IAsyncResult result) {
            return base.Channel.EndNameTags(result);
        }
        
        private System.IAsyncResult OnBeginNameTags(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginNameTags(callback, asyncState);
        }
        
        private object[] OnEndNameTags(System.IAsyncResult result) {
            System.Data.DataTable retVal = this.EndNameTags(result);
            return new object[] {
                    retVal};
        }
        
        private void OnNameTagsCompleted(object state) {
            if ((this.NameTagsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.NameTagsCompleted(this, new NameTagsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void NameTagsAsync() {
            this.NameTagsAsync(null);
        }
        
        public void NameTagsAsync(object userState) {
            if ((this.onBeginNameTagsDelegate == null)) {
                this.onBeginNameTagsDelegate = new BeginOperationDelegate(this.OnBeginNameTags);
            }
            if ((this.onEndNameTagsDelegate == null)) {
                this.onEndNameTagsDelegate = new EndOperationDelegate(this.OnEndNameTags);
            }
            if ((this.onNameTagsCompletedDelegate == null)) {
                this.onNameTagsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnNameTagsCompleted);
            }
            base.InvokeAsync(this.onBeginNameTagsDelegate, null, this.onEndNameTagsDelegate, this.onNameTagsCompletedDelegate, userState);
        }
    }
}
