//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.ServiceCenter.ServiceCodeGenerator {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="table", Namespace="http://schemas.datacontract.org/2004/07/PW.DBCommon.Model")]
    [System.SerializableAttribute()]
    public partial class table : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string table_commentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string table_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string table_comment {
            get {
                return this.table_commentField;
            }
            set {
                if ((object.ReferenceEquals(this.table_commentField, value) != true)) {
                    this.table_commentField = value;
                    this.RaisePropertyChanged("table_comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string table_name {
            get {
                return this.table_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.table_nameField, value) != true)) {
                    this.table_nameField = value;
                    this.RaisePropertyChanged("table_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="column", Namespace="http://schemas.datacontract.org/2004/07/PW.DBCommon.Model")]
    [System.SerializableAttribute()]
    public partial class column : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> character_maximum_lengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string column_commentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string column_keyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string column_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string data_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string is_nullableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> ordinal_positionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> character_maximum_length {
            get {
                return this.character_maximum_lengthField;
            }
            set {
                if ((this.character_maximum_lengthField.Equals(value) != true)) {
                    this.character_maximum_lengthField = value;
                    this.RaisePropertyChanged("character_maximum_length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string column_comment {
            get {
                return this.column_commentField;
            }
            set {
                if ((object.ReferenceEquals(this.column_commentField, value) != true)) {
                    this.column_commentField = value;
                    this.RaisePropertyChanged("column_comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string column_key {
            get {
                return this.column_keyField;
            }
            set {
                if ((object.ReferenceEquals(this.column_keyField, value) != true)) {
                    this.column_keyField = value;
                    this.RaisePropertyChanged("column_key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string column_name {
            get {
                return this.column_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.column_nameField, value) != true)) {
                    this.column_nameField = value;
                    this.RaisePropertyChanged("column_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data_type {
            get {
                return this.data_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.data_typeField, value) != true)) {
                    this.data_typeField = value;
                    this.RaisePropertyChanged("data_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string is_nullable {
            get {
                return this.is_nullableField;
            }
            set {
                if ((object.ReferenceEquals(this.is_nullableField, value) != true)) {
                    this.is_nullableField = value;
                    this.RaisePropertyChanged("is_nullable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ordinal_position {
            get {
                return this.ordinal_positionField;
            }
            set {
                if ((this.ordinal_positionField.Equals(value) != true)) {
                    this.ordinal_positionField = value;
                    this.RaisePropertyChanged("ordinal_position");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCodeGenerator.IServiceCodeGenerator")]
    public interface IServiceCodeGenerator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCodeGenerator/queryTables", ReplyAction="http://tempuri.org/IServiceCodeGenerator/queryTablesResponse")]
        PW.ServiceCenter.ServiceCodeGenerator.table[] queryTables();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceCodeGenerator/queryTables", ReplyAction="http://tempuri.org/IServiceCodeGenerator/queryTablesResponse")]
        System.IAsyncResult BeginqueryTables(System.AsyncCallback callback, object asyncState);
        
        PW.ServiceCenter.ServiceCodeGenerator.table[] EndqueryTables(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCodeGenerator/queryViews", ReplyAction="http://tempuri.org/IServiceCodeGenerator/queryViewsResponse")]
        PW.ServiceCenter.ServiceCodeGenerator.table[] queryViews();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceCodeGenerator/queryViews", ReplyAction="http://tempuri.org/IServiceCodeGenerator/queryViewsResponse")]
        System.IAsyncResult BeginqueryViews(System.AsyncCallback callback, object asyncState);
        
        PW.ServiceCenter.ServiceCodeGenerator.table[] EndqueryViews(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCodeGenerator/queryColumns", ReplyAction="http://tempuri.org/IServiceCodeGenerator/queryColumnsResponse")]
        PW.ServiceCenter.ServiceCodeGenerator.column[] queryColumns(string tableName);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceCodeGenerator/queryColumns", ReplyAction="http://tempuri.org/IServiceCodeGenerator/queryColumnsResponse")]
        System.IAsyncResult BeginqueryColumns(string tableName, System.AsyncCallback callback, object asyncState);
        
        PW.ServiceCenter.ServiceCodeGenerator.column[] EndqueryColumns(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCodeGeneratorChannel : PW.ServiceCenter.ServiceCodeGenerator.IServiceCodeGenerator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class queryTablesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public queryTablesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PW.ServiceCenter.ServiceCodeGenerator.table[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PW.ServiceCenter.ServiceCodeGenerator.table[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class queryViewsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public queryViewsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PW.ServiceCenter.ServiceCodeGenerator.table[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PW.ServiceCenter.ServiceCodeGenerator.table[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class queryColumnsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public queryColumnsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PW.ServiceCenter.ServiceCodeGenerator.column[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PW.ServiceCenter.ServiceCodeGenerator.column[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCodeGeneratorClient : System.ServiceModel.ClientBase<PW.ServiceCenter.ServiceCodeGenerator.IServiceCodeGenerator>, PW.ServiceCenter.ServiceCodeGenerator.IServiceCodeGenerator {
        
        private BeginOperationDelegate onBeginqueryTablesDelegate;
        
        private EndOperationDelegate onEndqueryTablesDelegate;
        
        private System.Threading.SendOrPostCallback onqueryTablesCompletedDelegate;
        
        private BeginOperationDelegate onBeginqueryViewsDelegate;
        
        private EndOperationDelegate onEndqueryViewsDelegate;
        
        private System.Threading.SendOrPostCallback onqueryViewsCompletedDelegate;
        
        private BeginOperationDelegate onBeginqueryColumnsDelegate;
        
        private EndOperationDelegate onEndqueryColumnsDelegate;
        
        private System.Threading.SendOrPostCallback onqueryColumnsCompletedDelegate;
        
        public ServiceCodeGeneratorClient() {
        }
        
        public ServiceCodeGeneratorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCodeGeneratorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCodeGeneratorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCodeGeneratorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<queryTablesCompletedEventArgs> queryTablesCompleted;
        
        public event System.EventHandler<queryViewsCompletedEventArgs> queryViewsCompleted;
        
        public event System.EventHandler<queryColumnsCompletedEventArgs> queryColumnsCompleted;
        
        public PW.ServiceCenter.ServiceCodeGenerator.table[] queryTables() {
            return base.Channel.queryTables();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginqueryTables(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginqueryTables(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public PW.ServiceCenter.ServiceCodeGenerator.table[] EndqueryTables(System.IAsyncResult result) {
            return base.Channel.EndqueryTables(result);
        }
        
        private System.IAsyncResult OnBeginqueryTables(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginqueryTables(callback, asyncState);
        }
        
        private object[] OnEndqueryTables(System.IAsyncResult result) {
            PW.ServiceCenter.ServiceCodeGenerator.table[] retVal = this.EndqueryTables(result);
            return new object[] {
                    retVal};
        }
        
        private void OnqueryTablesCompleted(object state) {
            if ((this.queryTablesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.queryTablesCompleted(this, new queryTablesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void queryTablesAsync() {
            this.queryTablesAsync(null);
        }
        
        public void queryTablesAsync(object userState) {
            if ((this.onBeginqueryTablesDelegate == null)) {
                this.onBeginqueryTablesDelegate = new BeginOperationDelegate(this.OnBeginqueryTables);
            }
            if ((this.onEndqueryTablesDelegate == null)) {
                this.onEndqueryTablesDelegate = new EndOperationDelegate(this.OnEndqueryTables);
            }
            if ((this.onqueryTablesCompletedDelegate == null)) {
                this.onqueryTablesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnqueryTablesCompleted);
            }
            base.InvokeAsync(this.onBeginqueryTablesDelegate, null, this.onEndqueryTablesDelegate, this.onqueryTablesCompletedDelegate, userState);
        }
        
        public PW.ServiceCenter.ServiceCodeGenerator.table[] queryViews() {
            return base.Channel.queryViews();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginqueryViews(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginqueryViews(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public PW.ServiceCenter.ServiceCodeGenerator.table[] EndqueryViews(System.IAsyncResult result) {
            return base.Channel.EndqueryViews(result);
        }
        
        private System.IAsyncResult OnBeginqueryViews(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginqueryViews(callback, asyncState);
        }
        
        private object[] OnEndqueryViews(System.IAsyncResult result) {
            PW.ServiceCenter.ServiceCodeGenerator.table[] retVal = this.EndqueryViews(result);
            return new object[] {
                    retVal};
        }
        
        private void OnqueryViewsCompleted(object state) {
            if ((this.queryViewsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.queryViewsCompleted(this, new queryViewsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void queryViewsAsync() {
            this.queryViewsAsync(null);
        }
        
        public void queryViewsAsync(object userState) {
            if ((this.onBeginqueryViewsDelegate == null)) {
                this.onBeginqueryViewsDelegate = new BeginOperationDelegate(this.OnBeginqueryViews);
            }
            if ((this.onEndqueryViewsDelegate == null)) {
                this.onEndqueryViewsDelegate = new EndOperationDelegate(this.OnEndqueryViews);
            }
            if ((this.onqueryViewsCompletedDelegate == null)) {
                this.onqueryViewsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnqueryViewsCompleted);
            }
            base.InvokeAsync(this.onBeginqueryViewsDelegate, null, this.onEndqueryViewsDelegate, this.onqueryViewsCompletedDelegate, userState);
        }
        
        public PW.ServiceCenter.ServiceCodeGenerator.column[] queryColumns(string tableName) {
            return base.Channel.queryColumns(tableName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginqueryColumns(string tableName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginqueryColumns(tableName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public PW.ServiceCenter.ServiceCodeGenerator.column[] EndqueryColumns(System.IAsyncResult result) {
            return base.Channel.EndqueryColumns(result);
        }
        
        private System.IAsyncResult OnBeginqueryColumns(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string tableName = ((string)(inValues[0]));
            return this.BeginqueryColumns(tableName, callback, asyncState);
        }
        
        private object[] OnEndqueryColumns(System.IAsyncResult result) {
            PW.ServiceCenter.ServiceCodeGenerator.column[] retVal = this.EndqueryColumns(result);
            return new object[] {
                    retVal};
        }
        
        private void OnqueryColumnsCompleted(object state) {
            if ((this.queryColumnsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.queryColumnsCompleted(this, new queryColumnsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void queryColumnsAsync(string tableName) {
            this.queryColumnsAsync(tableName, null);
        }
        
        public void queryColumnsAsync(string tableName, object userState) {
            if ((this.onBeginqueryColumnsDelegate == null)) {
                this.onBeginqueryColumnsDelegate = new BeginOperationDelegate(this.OnBeginqueryColumns);
            }
            if ((this.onEndqueryColumnsDelegate == null)) {
                this.onEndqueryColumnsDelegate = new EndOperationDelegate(this.OnEndqueryColumns);
            }
            if ((this.onqueryColumnsCompletedDelegate == null)) {
                this.onqueryColumnsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnqueryColumnsCompleted);
            }
            base.InvokeAsync(this.onBeginqueryColumnsDelegate, new object[] {
                        tableName}, this.onEndqueryColumnsDelegate, this.onqueryColumnsCompletedDelegate, userState);
        }
    }
}
