//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.ServiceCenter.ServiceMenu {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="menu", Namespace="http://schemas.datacontract.org/2004/07/PW.DBCommon.Model")]
    [System.SerializableAttribute()]
    public partial class menu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> CACHEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMPONENTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMPONENT_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CREATE_TIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> HIDDENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ICONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> I_FRAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MODULESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PATHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PERMISSIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> PIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> SORTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TYPEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> CACHE {
            get {
                return this.CACHEField;
            }
            set {
                if ((this.CACHEField.Equals(value) != true)) {
                    this.CACHEField = value;
                    this.RaisePropertyChanged("CACHE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMPONENT {
            get {
                return this.COMPONENTField;
            }
            set {
                if ((object.ReferenceEquals(this.COMPONENTField, value) != true)) {
                    this.COMPONENTField = value;
                    this.RaisePropertyChanged("COMPONENT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMPONENT_NAME {
            get {
                return this.COMPONENT_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.COMPONENT_NAMEField, value) != true)) {
                    this.COMPONENT_NAMEField = value;
                    this.RaisePropertyChanged("COMPONENT_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CREATE_TIME {
            get {
                return this.CREATE_TIMEField;
            }
            set {
                if ((this.CREATE_TIMEField.Equals(value) != true)) {
                    this.CREATE_TIMEField = value;
                    this.RaisePropertyChanged("CREATE_TIME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> HIDDEN {
            get {
                return this.HIDDENField;
            }
            set {
                if ((this.HIDDENField.Equals(value) != true)) {
                    this.HIDDENField = value;
                    this.RaisePropertyChanged("HIDDEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ICON {
            get {
                return this.ICONField;
            }
            set {
                if ((object.ReferenceEquals(this.ICONField, value) != true)) {
                    this.ICONField = value;
                    this.RaisePropertyChanged("ICON");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> I_FRAME {
            get {
                return this.I_FRAMEField;
            }
            set {
                if ((this.I_FRAMEField.Equals(value) != true)) {
                    this.I_FRAMEField = value;
                    this.RaisePropertyChanged("I_FRAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MODULES {
            get {
                return this.MODULESField;
            }
            set {
                if ((object.ReferenceEquals(this.MODULESField, value) != true)) {
                    this.MODULESField = value;
                    this.RaisePropertyChanged("MODULES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NAME {
            get {
                return this.NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.NAMEField, value) != true)) {
                    this.NAMEField = value;
                    this.RaisePropertyChanged("NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PATH {
            get {
                return this.PATHField;
            }
            set {
                if ((object.ReferenceEquals(this.PATHField, value) != true)) {
                    this.PATHField = value;
                    this.RaisePropertyChanged("PATH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PERMISSION {
            get {
                return this.PERMISSIONField;
            }
            set {
                if ((object.ReferenceEquals(this.PERMISSIONField, value) != true)) {
                    this.PERMISSIONField = value;
                    this.RaisePropertyChanged("PERMISSION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> PID {
            get {
                return this.PIDField;
            }
            set {
                if ((this.PIDField.Equals(value) != true)) {
                    this.PIDField = value;
                    this.RaisePropertyChanged("PID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> SORT {
            get {
                return this.SORTField;
            }
            set {
                if ((this.SORTField.Equals(value) != true)) {
                    this.SORTField = value;
                    this.RaisePropertyChanged("SORT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TYPE {
            get {
                return this.TYPEField;
            }
            set {
                if ((this.TYPEField.Equals(value) != true)) {
                    this.TYPEField = value;
                    this.RaisePropertyChanged("TYPE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageInfoOfmenuCLUigIiY", Namespace="http://schemas.datacontract.org/2004/07/PW.DBCommon.Model")]
    [System.SerializableAttribute()]
    public partial class PageInfoOfmenuCLUigIiY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PW.ServiceCenter.ServiceMenu.menu[] listField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PW.ServiceCenter.ServiceMenu.menu queryParamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalPageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PW.ServiceCenter.ServiceMenu.menu[] list {
            get {
                return this.listField;
            }
            set {
                if ((object.ReferenceEquals(this.listField, value) != true)) {
                    this.listField = value;
                    this.RaisePropertyChanged("list");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderName {
            get {
                return this.orderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.orderNameField, value) != true)) {
                    this.orderNameField = value;
                    this.RaisePropertyChanged("orderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pageIndex {
            get {
                return this.pageIndexField;
            }
            set {
                if ((this.pageIndexField.Equals(value) != true)) {
                    this.pageIndexField = value;
                    this.RaisePropertyChanged("pageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                if ((this.pageSizeField.Equals(value) != true)) {
                    this.pageSizeField = value;
                    this.RaisePropertyChanged("pageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PW.ServiceCenter.ServiceMenu.menu queryParams {
            get {
                return this.queryParamsField;
            }
            set {
                if ((object.ReferenceEquals(this.queryParamsField, value) != true)) {
                    this.queryParamsField = value;
                    this.RaisePropertyChanged("queryParams");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int totalCount {
            get {
                return this.totalCountField;
            }
            set {
                if ((this.totalCountField.Equals(value) != true)) {
                    this.totalCountField = value;
                    this.RaisePropertyChanged("totalCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int totalPage {
            get {
                return this.totalPageField;
            }
            set {
                if ((this.totalPageField.Equals(value) != true)) {
                    this.totalPageField = value;
                    this.RaisePropertyChanged("totalPage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMenu.IServiceMenu")]
    public interface IServiceMenu {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMenu/query", ReplyAction="http://tempuri.org/IServiceMenu/queryResponse")]
        PW.ServiceCenter.ServiceMenu.menu[] query(PW.ServiceCenter.ServiceMenu.menu record);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceMenu/query", ReplyAction="http://tempuri.org/IServiceMenu/queryResponse")]
        System.IAsyncResult Beginquery(PW.ServiceCenter.ServiceMenu.menu record, System.AsyncCallback callback, object asyncState);
        
        PW.ServiceCenter.ServiceMenu.menu[] Endquery(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMenu/queryPage", ReplyAction="http://tempuri.org/IServiceMenu/queryPageResponse")]
        PW.ServiceCenter.ServiceMenu.PageInfoOfmenuCLUigIiY queryPage(PW.ServiceCenter.ServiceMenu.PageInfoOfmenuCLUigIiY page);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceMenu/queryPage", ReplyAction="http://tempuri.org/IServiceMenu/queryPageResponse")]
        System.IAsyncResult BeginqueryPage(PW.ServiceCenter.ServiceMenu.PageInfoOfmenuCLUigIiY page, System.AsyncCallback callback, object asyncState);
        
        PW.ServiceCenter.ServiceMenu.PageInfoOfmenuCLUigIiY EndqueryPage(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMenu/deleteById", ReplyAction="http://tempuri.org/IServiceMenu/deleteByIdResponse")]
        int deleteById(int id);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceMenu/deleteById", ReplyAction="http://tempuri.org/IServiceMenu/deleteByIdResponse")]
        System.IAsyncResult BegindeleteById(int id, System.AsyncCallback callback, object asyncState);
        
        int EnddeleteById(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMenu/add", ReplyAction="http://tempuri.org/IServiceMenu/addResponse")]
        int add(PW.ServiceCenter.ServiceMenu.menu record);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceMenu/add", ReplyAction="http://tempuri.org/IServiceMenu/addResponse")]
        System.IAsyncResult Beginadd(PW.ServiceCenter.ServiceMenu.menu record, System.AsyncCallback callback, object asyncState);
        
        int Endadd(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMenu/updateById", ReplyAction="http://tempuri.org/IServiceMenu/updateByIdResponse")]
        int updateById(PW.ServiceCenter.ServiceMenu.menu record);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceMenu/updateById", ReplyAction="http://tempuri.org/IServiceMenu/updateByIdResponse")]
        System.IAsyncResult BeginupdateById(PW.ServiceCenter.ServiceMenu.menu record, System.AsyncCallback callback, object asyncState);
        
        int EndupdateById(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMenu/getById", ReplyAction="http://tempuri.org/IServiceMenu/getByIdResponse")]
        PW.ServiceCenter.ServiceMenu.menu getById(int id);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceMenu/getById", ReplyAction="http://tempuri.org/IServiceMenu/getByIdResponse")]
        System.IAsyncResult BegingetById(int id, System.AsyncCallback callback, object asyncState);
        
        PW.ServiceCenter.ServiceMenu.menu EndgetById(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceMenuChannel : PW.ServiceCenter.ServiceMenu.IServiceMenu, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class queryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public queryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PW.ServiceCenter.ServiceMenu.menu[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PW.ServiceCenter.ServiceMenu.menu[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class queryPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public queryPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PW.ServiceCenter.ServiceMenu.PageInfoOfmenuCLUigIiY Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PW.ServiceCenter.ServiceMenu.PageInfoOfmenuCLUigIiY)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class deleteByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public deleteByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class addCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public addCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class updateByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public updateByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PW.ServiceCenter.ServiceMenu.menu Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PW.ServiceCenter.ServiceMenu.menu)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceMenuClient : System.ServiceModel.ClientBase<PW.ServiceCenter.ServiceMenu.IServiceMenu>, PW.ServiceCenter.ServiceMenu.IServiceMenu {
        
        private BeginOperationDelegate onBeginqueryDelegate;
        
        private EndOperationDelegate onEndqueryDelegate;
        
        private System.Threading.SendOrPostCallback onqueryCompletedDelegate;
        
        private BeginOperationDelegate onBeginqueryPageDelegate;
        
        private EndOperationDelegate onEndqueryPageDelegate;
        
        private System.Threading.SendOrPostCallback onqueryPageCompletedDelegate;
        
        private BeginOperationDelegate onBegindeleteByIdDelegate;
        
        private EndOperationDelegate onEnddeleteByIdDelegate;
        
        private System.Threading.SendOrPostCallback ondeleteByIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginaddDelegate;
        
        private EndOperationDelegate onEndaddDelegate;
        
        private System.Threading.SendOrPostCallback onaddCompletedDelegate;
        
        private BeginOperationDelegate onBeginupdateByIdDelegate;
        
        private EndOperationDelegate onEndupdateByIdDelegate;
        
        private System.Threading.SendOrPostCallback onupdateByIdCompletedDelegate;
        
        private BeginOperationDelegate onBegingetByIdDelegate;
        
        private EndOperationDelegate onEndgetByIdDelegate;
        
        private System.Threading.SendOrPostCallback ongetByIdCompletedDelegate;
        
        public ServiceMenuClient() {
        }
        
        public ServiceMenuClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceMenuClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMenuClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMenuClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<queryCompletedEventArgs> queryCompleted;
        
        public event System.EventHandler<queryPageCompletedEventArgs> queryPageCompleted;
        
        public event System.EventHandler<deleteByIdCompletedEventArgs> deleteByIdCompleted;
        
        public event System.EventHandler<addCompletedEventArgs> addCompleted;
        
        public event System.EventHandler<updateByIdCompletedEventArgs> updateByIdCompleted;
        
        public event System.EventHandler<getByIdCompletedEventArgs> getByIdCompleted;
        
        public PW.ServiceCenter.ServiceMenu.menu[] query(PW.ServiceCenter.ServiceMenu.menu record) {
            return base.Channel.query(record);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginquery(PW.ServiceCenter.ServiceMenu.menu record, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginquery(record, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public PW.ServiceCenter.ServiceMenu.menu[] Endquery(System.IAsyncResult result) {
            return base.Channel.Endquery(result);
        }
        
        private System.IAsyncResult OnBeginquery(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PW.ServiceCenter.ServiceMenu.menu record = ((PW.ServiceCenter.ServiceMenu.menu)(inValues[0]));
            return this.Beginquery(record, callback, asyncState);
        }
        
        private object[] OnEndquery(System.IAsyncResult result) {
            PW.ServiceCenter.ServiceMenu.menu[] retVal = this.Endquery(result);
            return new object[] {
                    retVal};
        }
        
        private void OnqueryCompleted(object state) {
            if ((this.queryCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.queryCompleted(this, new queryCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void queryAsync(PW.ServiceCenter.ServiceMenu.menu record) {
            this.queryAsync(record, null);
        }
        
        public void queryAsync(PW.ServiceCenter.ServiceMenu.menu record, object userState) {
            if ((this.onBeginqueryDelegate == null)) {
                this.onBeginqueryDelegate = new BeginOperationDelegate(this.OnBeginquery);
            }
            if ((this.onEndqueryDelegate == null)) {
                this.onEndqueryDelegate = new EndOperationDelegate(this.OnEndquery);
            }
            if ((this.onqueryCompletedDelegate == null)) {
                this.onqueryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnqueryCompleted);
            }
            base.InvokeAsync(this.onBeginqueryDelegate, new object[] {
                        record}, this.onEndqueryDelegate, this.onqueryCompletedDelegate, userState);
        }
        
        public PW.ServiceCenter.ServiceMenu.PageInfoOfmenuCLUigIiY queryPage(PW.ServiceCenter.ServiceMenu.PageInfoOfmenuCLUigIiY page) {
            return base.Channel.queryPage(page);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginqueryPage(PW.ServiceCenter.ServiceMenu.PageInfoOfmenuCLUigIiY page, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginqueryPage(page, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public PW.ServiceCenter.ServiceMenu.PageInfoOfmenuCLUigIiY EndqueryPage(System.IAsyncResult result) {
            return base.Channel.EndqueryPage(result);
        }
        
        private System.IAsyncResult OnBeginqueryPage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PW.ServiceCenter.ServiceMenu.PageInfoOfmenuCLUigIiY page = ((PW.ServiceCenter.ServiceMenu.PageInfoOfmenuCLUigIiY)(inValues[0]));
            return this.BeginqueryPage(page, callback, asyncState);
        }
        
        private object[] OnEndqueryPage(System.IAsyncResult result) {
            PW.ServiceCenter.ServiceMenu.PageInfoOfmenuCLUigIiY retVal = this.EndqueryPage(result);
            return new object[] {
                    retVal};
        }
        
        private void OnqueryPageCompleted(object state) {
            if ((this.queryPageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.queryPageCompleted(this, new queryPageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void queryPageAsync(PW.ServiceCenter.ServiceMenu.PageInfoOfmenuCLUigIiY page) {
            this.queryPageAsync(page, null);
        }
        
        public void queryPageAsync(PW.ServiceCenter.ServiceMenu.PageInfoOfmenuCLUigIiY page, object userState) {
            if ((this.onBeginqueryPageDelegate == null)) {
                this.onBeginqueryPageDelegate = new BeginOperationDelegate(this.OnBeginqueryPage);
            }
            if ((this.onEndqueryPageDelegate == null)) {
                this.onEndqueryPageDelegate = new EndOperationDelegate(this.OnEndqueryPage);
            }
            if ((this.onqueryPageCompletedDelegate == null)) {
                this.onqueryPageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnqueryPageCompleted);
            }
            base.InvokeAsync(this.onBeginqueryPageDelegate, new object[] {
                        page}, this.onEndqueryPageDelegate, this.onqueryPageCompletedDelegate, userState);
        }
        
        public int deleteById(int id) {
            return base.Channel.deleteById(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegindeleteById(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegindeleteById(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EnddeleteById(System.IAsyncResult result) {
            return base.Channel.EnddeleteById(result);
        }
        
        private System.IAsyncResult OnBegindeleteById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return this.BegindeleteById(id, callback, asyncState);
        }
        
        private object[] OnEnddeleteById(System.IAsyncResult result) {
            int retVal = this.EnddeleteById(result);
            return new object[] {
                    retVal};
        }
        
        private void OndeleteByIdCompleted(object state) {
            if ((this.deleteByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.deleteByIdCompleted(this, new deleteByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void deleteByIdAsync(int id) {
            this.deleteByIdAsync(id, null);
        }
        
        public void deleteByIdAsync(int id, object userState) {
            if ((this.onBegindeleteByIdDelegate == null)) {
                this.onBegindeleteByIdDelegate = new BeginOperationDelegate(this.OnBegindeleteById);
            }
            if ((this.onEnddeleteByIdDelegate == null)) {
                this.onEnddeleteByIdDelegate = new EndOperationDelegate(this.OnEnddeleteById);
            }
            if ((this.ondeleteByIdCompletedDelegate == null)) {
                this.ondeleteByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OndeleteByIdCompleted);
            }
            base.InvokeAsync(this.onBegindeleteByIdDelegate, new object[] {
                        id}, this.onEnddeleteByIdDelegate, this.ondeleteByIdCompletedDelegate, userState);
        }
        
        public int add(PW.ServiceCenter.ServiceMenu.menu record) {
            return base.Channel.add(record);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginadd(PW.ServiceCenter.ServiceMenu.menu record, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginadd(record, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int Endadd(System.IAsyncResult result) {
            return base.Channel.Endadd(result);
        }
        
        private System.IAsyncResult OnBeginadd(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PW.ServiceCenter.ServiceMenu.menu record = ((PW.ServiceCenter.ServiceMenu.menu)(inValues[0]));
            return this.Beginadd(record, callback, asyncState);
        }
        
        private object[] OnEndadd(System.IAsyncResult result) {
            int retVal = this.Endadd(result);
            return new object[] {
                    retVal};
        }
        
        private void OnaddCompleted(object state) {
            if ((this.addCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.addCompleted(this, new addCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void addAsync(PW.ServiceCenter.ServiceMenu.menu record) {
            this.addAsync(record, null);
        }
        
        public void addAsync(PW.ServiceCenter.ServiceMenu.menu record, object userState) {
            if ((this.onBeginaddDelegate == null)) {
                this.onBeginaddDelegate = new BeginOperationDelegate(this.OnBeginadd);
            }
            if ((this.onEndaddDelegate == null)) {
                this.onEndaddDelegate = new EndOperationDelegate(this.OnEndadd);
            }
            if ((this.onaddCompletedDelegate == null)) {
                this.onaddCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnaddCompleted);
            }
            base.InvokeAsync(this.onBeginaddDelegate, new object[] {
                        record}, this.onEndaddDelegate, this.onaddCompletedDelegate, userState);
        }
        
        public int updateById(PW.ServiceCenter.ServiceMenu.menu record) {
            return base.Channel.updateById(record);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginupdateById(PW.ServiceCenter.ServiceMenu.menu record, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginupdateById(record, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public int EndupdateById(System.IAsyncResult result) {
            return base.Channel.EndupdateById(result);
        }
        
        private System.IAsyncResult OnBeginupdateById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PW.ServiceCenter.ServiceMenu.menu record = ((PW.ServiceCenter.ServiceMenu.menu)(inValues[0]));
            return this.BeginupdateById(record, callback, asyncState);
        }
        
        private object[] OnEndupdateById(System.IAsyncResult result) {
            int retVal = this.EndupdateById(result);
            return new object[] {
                    retVal};
        }
        
        private void OnupdateByIdCompleted(object state) {
            if ((this.updateByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.updateByIdCompleted(this, new updateByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void updateByIdAsync(PW.ServiceCenter.ServiceMenu.menu record) {
            this.updateByIdAsync(record, null);
        }
        
        public void updateByIdAsync(PW.ServiceCenter.ServiceMenu.menu record, object userState) {
            if ((this.onBeginupdateByIdDelegate == null)) {
                this.onBeginupdateByIdDelegate = new BeginOperationDelegate(this.OnBeginupdateById);
            }
            if ((this.onEndupdateByIdDelegate == null)) {
                this.onEndupdateByIdDelegate = new EndOperationDelegate(this.OnEndupdateById);
            }
            if ((this.onupdateByIdCompletedDelegate == null)) {
                this.onupdateByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnupdateByIdCompleted);
            }
            base.InvokeAsync(this.onBeginupdateByIdDelegate, new object[] {
                        record}, this.onEndupdateByIdDelegate, this.onupdateByIdCompletedDelegate, userState);
        }
        
        public PW.ServiceCenter.ServiceMenu.menu getById(int id) {
            return base.Channel.getById(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetById(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetById(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public PW.ServiceCenter.ServiceMenu.menu EndgetById(System.IAsyncResult result) {
            return base.Channel.EndgetById(result);
        }
        
        private System.IAsyncResult OnBegingetById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return this.BegingetById(id, callback, asyncState);
        }
        
        private object[] OnEndgetById(System.IAsyncResult result) {
            PW.ServiceCenter.ServiceMenu.menu retVal = this.EndgetById(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetByIdCompleted(object state) {
            if ((this.getByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getByIdCompleted(this, new getByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getByIdAsync(int id) {
            this.getByIdAsync(id, null);
        }
        
        public void getByIdAsync(int id, object userState) {
            if ((this.onBegingetByIdDelegate == null)) {
                this.onBegingetByIdDelegate = new BeginOperationDelegate(this.OnBegingetById);
            }
            if ((this.onEndgetByIdDelegate == null)) {
                this.onEndgetByIdDelegate = new EndOperationDelegate(this.OnEndgetById);
            }
            if ((this.ongetByIdCompletedDelegate == null)) {
                this.ongetByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetByIdCompleted);
            }
            base.InvokeAsync(this.onBegingetByIdDelegate, new object[] {
                        id}, this.onEndgetByIdDelegate, this.ongetByIdCompletedDelegate, userState);
        }
    }
}
