//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.DBCommon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class answers
    {
        public string answer_id { get; set; }
        public string answer_no { get; set; }
        public string answer_content { get; set; }
        public Nullable<decimal> answer_score { get; set; }
        public string upuser { get; set; }
        public Nullable<System.DateTime> uptime { get; set; }
        public string question_id { get; set; }
    }
}
