//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.DBCommon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dept
    {
        public long ID { get; set; }
        public string NAME { get; set; }
        public Nullable<long> PID { get; set; }
        public Nullable<bool> ENABLED { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
    }
}
