//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.DBCommon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class general_workflow_steps
    {
        public int ORIGREC { get; set; }
        public string WORKFLOWCODE { get; set; }
        public string USRNAM { get; set; }
        public Nullable<int> NUMBEROOFDAYS { get; set; }
        public string STEPCODE { get; set; }
        public Nullable<int> SORTER { get; set; }
        public string JOBDESCRIPTION { get; set; }
        public string GOTOSTEPS { get; set; }
        public string SIGNATURETYPE { get; set; }
        public string ORIGSTS { get; set; }
        public string TREEAUTH { get; set; }
        public string STEPSTATUS { get; set; }
        public string STEPNAME { get; set; }
        public string EXECUTEACTION { get; set; }
        public string EXECUTEACTION1 { get; set; }
        public string EXECUTEACTION2 { get; set; }
        public string EXECUTEACTION3 { get; set; }
        public string CONSOLEITEM { get; set; }
        public string DESTINATIONTYPE { get; set; }
        public string GROUPNAME { get; set; }
        public string STEPDISPSTATUS { get; set; }
        public string GROUPTABLE { get; set; }
        public string GROUPTABLEFIELD1 { get; set; }
        public string GROUPTABLEFIELD2 { get; set; }
        public string GROUPTABLEFIELD3 { get; set; }
        public string MYLIMSSTS { get; set; }
        public string COMMENTNAME { get; set; }
        public string FUNCCODE { get; set; }
        public string BYSERVGRP { get; set; }
        public string ROLES { get; set; }
    }
}
