//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.DBCommon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class general_workflowstepdet
    {
        public int ORIGREC { get; set; }
        public string ORIGSTS { get; set; }
        public string WORKFLOWCODE { get; set; }
        public string STEPCODE { get; set; }
        public string DISPOSITIONNAME { get; set; }
        public string DISPOSITIONCODE { get; set; }
        public string TOSTEPCODE { get; set; }
        public Nullable<int> INVESTIGATIONCODE { get; set; }
        public string TOSTEPNAME { get; set; }
        public string EXECUTEACTION { get; set; }
        public Nullable<int> SORTER { get; set; }
        public string VERIFYACTION { get; set; }
        public string REASONS { get; set; }
        public string ISREJECT { get; set; }
        public string VISIBLE { get; set; }
        public string AUDITTYPE { get; set; }
        public string NOTNULLCOMMENT { get; set; }
        public string DISPFLAG { get; set; }
        public string STEPDETCAT { get; set; }
        public string REQUIREREASON { get; set; }
        public string ISMULTIAUDIT { get; set; }
        public string ISAUDITUSER { get; set; }
        public string CALCUL { get; set; }
        public string BUSINESSTYPE { get; set; }
        public string MESSAGETEXT { get; set; }
        public string MESSAGEUSER { get; set; }
        public string ISSENDMES { get; set; }
        public string ISMULTIPLE { get; set; }
        public string VERIFYCALCNO { get; set; }
    }
}
