//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.DBCommon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class general_workflow_func
    {
        public int ORIGREC { get; set; }
        public string ORIGSTS { get; set; }
        public string WORKFLOWCODE { get; set; }
        public string STEPCODE { get; set; }
        public string CALCDESC { get; set; }
        public string CALCNAME { get; set; }
        public string CALCUL { get; set; }
        public string CONTROLID { get; set; }
        public string ACTIONTYPE { get; set; }
        public string REPLACE { get; set; }
        public string CONTROLTYPE { get; set; }
    }
}
