//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.DBCommon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class general_workflows
    {
        public int ORIGREC { get; set; }
        public string WORKFLOWCODE { get; set; }
        public string WORKFLOWDESC { get; set; }
        public string WORKFLOWNAME { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<int> VERSION { get; set; }
        public string APPLICATIONREF { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string ORIGSTS { get; set; }
        public string TABLERELATED { get; set; }
        public string STATUSFIELD { get; set; }
        public string DISSTATUSFIELD { get; set; }
        public string NEEDESIGN { get; set; }
        public string REJECTFIELD { get; set; }
        public string RETIRED { get; set; }
    }
}
