//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.DBCommon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class papers
    {
        public string paper_id { get; set; }
        public string paper_title { get; set; }
        public string paper_description { get; set; }
        public string upuser { get; set; }
        public Nullable<System.DateTime> uptime { get; set; }
        public string group_id { get; set; }
        public string isshow { get; set; }
        public Nullable<int> paper_no { get; set; }
    }
}
