//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.DBCommon.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qdbEntities : DbContext
    {
        public qdbEntities()
            : base("name=qdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dept> dept { get; set; }
        public virtual DbSet<dict> dict { get; set; }
        public virtual DbSet<dict_detail> dict_detail { get; set; }
        public virtual DbSet<general_workflow_func> general_workflow_func { get; set; }
        public virtual DbSet<general_workflow_steps> general_workflow_steps { get; set; }
        public virtual DbSet<general_workflows> general_workflows { get; set; }
        public virtual DbSet<general_workflowstepdet> general_workflowstepdet { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<roles_depts> roles_depts { get; set; }
        public virtual DbSet<roles_menus> roles_menus { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<user_avatar> user_avatar { get; set; }
        public virtual DbSet<users_roles> users_roles { get; set; }
    }
}
