//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.DBCommon.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qdbEntities : DbContext
    {
        public qdbEntities()
            : base("name=qdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<answers> answers { get; set; }
        public virtual DbSet<papers> papers { get; set; }
        public virtual DbSet<questions> questions { get; set; }
        public virtual DbSet<results> results { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
