//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.DBCommon.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public long ID { get; set; }
        public Nullable<long> AVATAR_ID { get; set; }
        public string EMAIL { get; set; }
        public Nullable<long> ENABLED { get; set; }
        public string PASSWORD { get; set; }
        public string USERNAME { get; set; }
        public Nullable<long> DEPT_ID { get; set; }
        public string PHONE { get; set; }
        public Nullable<long> JOB_ID { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public Nullable<System.DateTime> LAST_PASSWORD_RESET_TIME { get; set; }
        public string NICK_NAME { get; set; }
        public string SEX { get; set; }
    }
}
